-- GET TOTAL AMOUNT OF CUSTOMER STORED IN ANOTHER VARIABLE

DROP PROCEDURE SP_GETTOTALAMOUNTOFCUSTOMER
DELIMITER //
CREATE PROCEDURE SP_GETTOTALAMOUNTOFCUSTOMER(IN CUST_ID INT,OUT TOT_AMT INT)
BEGIN 
SELECT SUM(AMOUNT) INTO TOT_AMT FROM PAYMENT WHERE CUSTOMER_ID;
END
//
DELIMITER ;

CALL SP_GETTOTALAMOUNTOFCUSTOMER(3,@TA)
SELECT @TA
SELECT CUSTOMER_ID,AMOUNT FROM PAYMENT where Amount=0.99 ;
