-- Determine the total revenue generated by each store.

select * from store


select sum(amount) ,payment.customer_id,staff.store_id  from payment join staff 
on payment.staff_id=staff.staff_id join store
on store.store_id=staff.store_id
group by staff.store_id
