-- Calculate Revenue by Category
-- Design a stored procedure that calculates the total revenue generated by each film category. 
-- The procedure should output a report showing the revenue for each category and 
-- the percentage of total revenue it represents.

delimiter //
create procedure sumAmount()

 begin
select TIMESTAMP ,sum(amount) from payment join rental on rental.rental_id=payment.rental_Id
join inventory on inventory.inventory_id=rental.inventory_id 
join film on film.film_id=inventory.film_id 
JOIN FILM_CATEGORY ON FILM.FILM_ID =FILM_CATEGORY.FILM_ID
JOIN CATEGORY ON CATEGORY.CATEGORY_ID =FILM_CATEGORY.CATEGORY_ID
GROUP BY   TIMESTAMP ;

  END
  //
  delimiter ;
  call sumAmount
  DROP PROCEDURE sumAmount
